# Generated by Django 3.2 on 2022-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputemo',
            fields=[
                ('emo_id', models.AutoField(primary_key=True, serialize=False)),
                ('emo_name', models.CharField(default='emotion fining', max_length=150)),
                ('date_when_upload', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='my_data/')),
            ],
        ),
    ]
